In [1]:
import pandas as pd
import seaborn as sns

In [3]:
df = pd.read_csv("club.csv")

In [7]:
df.sample(10)

,Club Name,Competition Name,Squad Size,Average Age Of Players,Market Value Of Club In Millions(£),Average Market Value Of Players In Millions(£),Market Value Of Top 18 Players In Millions(£)
41,ACF Fiorentina,Serie A,26,27.0,228.42,8.79,214.02
16,RB Leipzig,Bundesliga,29,24.1,447.80,15.44,408.15
74,Fenerbahce SK,Süper Lig,32,25.5,114.17,3.57,102.78
56,Shakhtar Donetsk,Premier Liga,29,25.8,165.60,5.71,149.85
31,SS Lazio,Serie A,33,27.6,280.17,8.49,257.67
55,Torino FC,Serie A,30,26.1,167.33,5.58,150.30
15,SSC Napoli,Serie A,26,27.7,467.01,17.96,444.60
6,Real Madrid,LaLiga,27,27.3,680.40,25.20,610.20
94,FC Girondins Bordeaux,Ligue 1,30,25.3,89.55,2.99,78.75
42,Olympique Marseille,Ligue 1,27,24.0,225.27,8.34,210.60